az_dirs:
  - "image"

az_envs:
  ont: "aks-davebbn1-ont-weu-01"
  acc: "aks-davebbn1-acc-weu-01"
  prd: "aks-davebbn1-prd-weu-01"

az_user:
  name: azzie
  uid: 1005
  home: /home/azzie
  password: '!'
  dirs: "{{ az_dirs }}"

az_img:
  base: "mcr.microsoft.com/azure-cli:2.31.0"
  docker_file_template: "Dockerfile.azure-client.j2"
  build_dir: "{{ az_user.home }}/image"
  name: "ams-az"
  tag: wonderbox
