wifi_networks:
  - name: Home
    id: Ziggo0030533
    uuid: b1fb71e4-c907-4e15-b177-1eb16696fa0f
    ssid: Ziggo0030533
    psk: Rm4dwysmmJtn

  - name: Freak Mobile
    id: freak mobile
    uuid: uuid=980c8f27-a1d4-4d16-88d6-af350d0b0cb1
    ssid: freak mobile
    psk: bier is goed


vpns:
  - name: AmsterdamVPN
    uuid: 454b903c-9ea9-40e3-b577-b3529cbeec4b
    autoconnect: true
    ca: /home/ahimsa/.cert/nm-openvpn/vpn-ca.pem
    cert: /home/ahimsa/.cert/nm-openvpn/vpn-cert.pem
    dev: tun
    key: /home/ahimsa/.cert/nm-openvpn/vpn-key.pem
    remote: 83.96.212.24:1194:udp
    ta: /home/ahimsa/.cert/nm-openvpn/vpn-tls-auth.pem
    ta-dir: 1
    username: jfranx
    verify-x509-name: subject:C=NL, ST=Noord-Holland, L=Amsterdam, O=Datapunt, emailAddress=datapunt@amsterdam.nl, CN=vpn.datapunt2.amsterdam.nl
    service-type: org.freedesktop.NetworkManager.openvpn
