---
# Run tasks
#
# - name: pre-flight checks
#   import_tasks: pre_flight.yml
#   tags: "pf"

- name: My System
  become: yes
  import_tasks: system.yml
  tags:
    - "never"
    - "system"

- name: System services
  become: yes
  import_tasks: system_services.yml
  tags:
    - "never"
    - "system"

- name: Azure containers
  become: yes
  import_tasks: containers.yml
  tags: 
    - "never" 
    - "system"

- name: user home
  become: yes
  become_user: "{{ my_user }}"
  import_tasks: user_home.yml
  tags: 
    - "never"
    - "user"

- name: user VPN
  import_tasks: user_vpn.yml
  tags: 
    - "never"
    - "user"


