- name: Load variables for system
  include_vars:
    file: system.yml

- name: install desired packages
  pacman:
    pkg: "{{ pkgs }}"
    state: present

- name: Xorg files
  copy:
    src: "{{ item }}"
    dest: "/etc/X11/xorg.conf.d/"
  with_fileglob: 
    - "files/etc/X11/xorg.conf.d/*.conf"

- name: Udev rules
  copy:
    src: "{{ item }}"
    dest: "/etc/udev/rules.d/"
  with_fileglob: 
    - "files/etc/udev/rules.d/*.rule"    