- name: Load variables for system
  include_vars:
    file: system.yml

- name: Load general variables
  include_vars:
    file: general.yml

- name: install desired packages
  pacman:
    pkg: "{{ pkgs }}"
    state: present

- name: pip packages
  pip:
    name: "{{ pip_modules }}"
    state: present

- name: Resolver
  template:
    src: templates/etc/resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    mode: 0644

- name: Xorg files
  copy:
    src: "{{ item }}"
    dest: "/etc/X11/xorg.conf.d/"
  with_fileglob: 
    - "files/etc/X11/xorg.conf.d/*.conf"

- name: Udev rules
  copy:
    src: "{{ item }}"
    dest: "/etc/udev/rules.d/"
  with_fileglob: 
    - "files/etc/udev/rules.d/*.rule"    

- name: User
  user:
    name: "{{ my_user }}"
    comment: "Henry likes broccoli"
    append: yes
    shell: "{{ my_shell }}"
    groups: "{{ user_groups }}"
