- name: stop unwanted goblins
  systemd:
    name: "{{ item }}"
    enabled: no
    state: stopped
  with_items: "{{ stopped }}"

- name: start the music
  systemd:
    name: "{{ item }}"
    enabled: no
    state: started
  with_items: "{{ started }}"

- name: adding existing user to groups
  user:
    name: '{{ my_user }}'
    groups: "{{ item }}"
    append: yes
  with_items: "{{ user_groups }}"