- name: Load variables for system
  include_vars:
    file: system.yml

- name: Load general variables
  include_vars:
    file: general.yml

- name: install desired packages
  pacman:
    pkg: "{{ pkgs }}"
    state: present

- name: pip packages
  pip:
    name: "{{ pip_modules }}"
    state: present

- name: Resolver
  template:
    src: templates/etc/resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    mode: 0644

- name: DnsCrypt conf
  copy:
    src: "files/etc/dnscrypt-proxy.toml"
    dest: "/etc/dnscrypt-proxy/dnscrypt-proxy.toml"
    owner: "root"
    group: "root"
    mode: 0644
  notify:
    - restart dnscrypt

- name: DnsCrypt unit overrides
  copy:
    src: "files/etc/systemd/dnscrypt-proxy-override.conf"
    dest: "/etc/systemd/system/dnscrypt-proxy.service.d/override.conf"
    owner: "root"
    group: "root"
    mode: 0644
  notify:
    - reload systemd
    - restart dnscrypt

- name: Xorg files
  copy:
    src: "{{ item }}"
    dest: "/etc/X11/xorg.conf.d/"
  with_fileglob: 
    - "files/etc/X11/xorg.conf.d/*.conf"

- name: Udev rules
  copy:
    src: "{{ item }}"
    dest: "/etc/udev/rules.d/"
  with_fileglob: 
    - "files/etc/udev/rules.d/*.rule"    

- name: User
  user:
    name: "{{ my_user }}"
    comment: "Henry likes broccoli"
    append: yes
    shell: "{{ my_shell }}"
    groups: "{{ user_groups }}"
