- name: Load variables for system
  include_vars:
    file: system.yml

- name: Load general variables
  include_vars:
    file: general.yml

- name: install desired packages
  pacman:
    pkg: "{{ pkgs }}"
    state: present

- name: pip packages
  pip:
    name: "{{ pip_modules }}"
    state: present

- name: tor proxy
  template:
    src: templates/etc/torrc.j2
    dest: /etc/tor/torrc
    owner: root
    mode: 0644
  notify:
    - restart tor

- name: tor dns in hostsfile
  lineinfile:
    path: "/etc/hosts"
    create: no
    state: present
    regexp: "^127.0.0.1"
    line: "127.0.0.1 localhost {{ ansible_hostname }} {{ tor_dns.resolver }}"

- name: socat tor DNS proxy
  template:
    src: templates/systemd/{{ tor_dns.proxy_unitfile }}.j2
    dest: /etc/systemd/system/{{ tor_dns.proxy_unitfile }}
    owner: root
    mode: 0655
  register: dns_proxy_unit

- name: get the proxy going
  systemd:
    name: "{{ tor_dns.proxy_unitfile }}"
    enabled: yes
    state: restarted
    daemon_reload: yes
  when: dns_proxy_unit.changed

- name: Xorg files
  copy:
    src: "{{ item }}"
    dest: "/etc/X11/xorg.conf.d/"
  with_fileglob: 
    - "files/etc/X11/xorg.conf.d/*.conf"

- name: Udev rules
  copy:
    src: "{{ item }}"
    dest: "/etc/udev/rules.d/"
  with_fileglob: 
    - "files/etc/udev/rules.d/*.rule"    

- name: User
  user:
    name: "{{ my_user }}"
    comment: "Henry likes broccoli"
    append: yes
    shell: "{{ my_shell }}"
    groups: "{{ user_groups }}"
