- name: Load variables
  include_vars:
    file: home.yml

- name: ProtonVPN script
  copy:
    src: "files/user/bin/randomize_pvpn"
    dest: "{{ home_dir }}/bin/randomize_pvpn"
    owner: "{{ my_user }}"
    group: "{{ my_user }}"
    mode: 0750


- name: User config dir
  file:
    path: "{{ home_dir }}/.config/protonvpn"
    state: directory
    mode: "0700"

- name: User config file
  template:
    src: "templates/systemd/user/protonvpn_user_conf.json.j2"
    dest: "{{ home_dir }}/.config/protonvpn/user_configurations.json"
    mode: "0644"

- name: Peering randomize service
  template: 
    src: "templates/systemd/user/randomize_pvpn.service.j2"
    dest: "{{ home_dir }}/.config/systemd/user/randomize_pvpn.service"
  register: service
  notify:
    - reload user-systemd

- name: Randomizer systemd timer unit
  template: 
    src: "templates/systemd/user/randomize_pvpn.timer.j2"
    dest: "{{ home_dir }}/.config/systemd/user/randomize_pvpn.timer"
  register: timer
  notify:
    - reload user-systemd

- name: Enable ProtonVPN randomizer timer
  systemd:
    name: randomize_pvpn.timer
    scope: user
    daemon_reload: yes
    enabled: yes
    force: yes
    state: started

- name: ProtonVPN randomizer service
  systemd:
    name: randomize_pvpn.service
    scope: user
    daemon_reload: yes
    force: yes
    state: restarted
  when: service.changed

