- name: Load variables for home
  include_vars:
    file: home.yml

- name: Xfce4 whisker menu
  copy:
    src: "{{ role_path }}/files/xfce4/whiskermenu-8.rc"
    dest: "{{ home_dir }}/.config/xfce4/panel/whiskermenu-8.rc"

- name: Xfce4 keyboard shortcuts
  copy:
    src: "{{ role_path }}/files/xfce4/xfce4-keyboard-shortcuts.xml"
    dest: "{{ home_dir }}/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-keyboard-shortcuts.xml"


- name: pip packages
  pip:
    name: "{{ pip_modules }}"
    state: present
    executable: "{{ home_dir }}/{{ venv }}/bin/pip"

- name: venv bin in path
  lineinfile:
    path: "{{ home_dir }}/.bashrc"
    state: present
    regexp: "^PATH="
    line: "PATH=$PATH:{{ home_dir }}/{{ venv}}/bin"

- name: Python alias
  lineinfile:
    path: "{{ home_dir }}/.bashrc"
    state: present
    regexp: "^alias python="
    line: "alias python=\"{{ home_dir }}/{{ venv}}/bin/python\""

- name: PiP alias
  lineinfile:
    path: "{{ home_dir }}/.bashrc"
    state: present
    regexp: "^alias pip="
    line: "alias pip=\"{{ home_dir }}/{{ venv}}/bin/pip\""

- name: K9S alias
  lineinfile:
    path: "{{ home_dir }}/.bashrc"
    state: present
    regexp: "^alias k9s="
    line: "alias k9s=\"docker run derailed/k9s\""

- name: docker
  lineinfile:
    path: "{{ home_dir }}/.bashrc"
    state: present
    regexp: "^alias d="
    line: "alias d=\"docker\""

- name: terraform
  lineinfile:
    path: "{{ home_dir }}/.bashrc"
    state: present
    regexp: "^alias tf="
    line: "alias tf=\"docker run --mount type=bind,source={{ home_dir }}/{{ container_data_dir }}/terraform,destination=/workspace -ti {{ tf_image }}\""

- name: User directories
  file:
    path: "{{ item }}"
    owner: "{{ my_user }}"
    state: directory
    mode: "0700"
  with_items: "{{ [home_dir] | product(user_home_dirs) | map('join') | list }}"

- name: Desktop file templates
  template:
    src: "{{ item }}"
    dest: "{{ home_dir }}/{{ user_app_dir }}/"
  with_fileglob: 
    - "templates/desktop/*.desktop"