- name: Load variables
  include_vars:
    file: home.yml


- name: Xfce4 keyboard shortcuts
  copy:
    src: "{{ role_path }}/files/xfce4/xfce4-keyboard-shortcuts.xml"
    dest: "{{ home_dir }}/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-keyboard-shortcuts.xml"

- name: pip packages
  pip:
    name: "{{ pip_modules }}"
    state: present
    executable: "{{ home_dir }}/{{ venv }}/bin/pip"

- name: SSH dir
  file:
    path: "{{ home_dir }}/.ssh"
    state: directory
    owner: "{{ my_user }}"
    group: "{{ my_user }}"
    mode: "0700"

- name: SSH known hosts
  lineinfile:
    path: "{{ home_dir }}/.ssh/known_hosts"
    create: yes
    state: present
    regexp: "^{{ item.host }}"
    line: "{{item.host}} {{item.pubkey}}"
  with_items: 
    - "{{ ssh_known_hosts }}"

- name: SSH client config
  template: 
    src: "templates/ssh_conf.j2"
    dest: "{{ home_dir }}/.ssh/config"

- name: Bashrc
  lineinfile:
    path: "{{ home_dir }}/.bashrc"
    state: present
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - "{{ bashrc_entries }}"

- name: User directories
  file:
    path: "{{ item }}"
    owner: "{{ my_user }}"
    state: directory
    mode: "0700"
  with_items: "{{ [home_dir] | product(user_home_dirs) | map('join') | list }}"


- name: Render Chrome Apps
  template:
    src: "templates/chrome-app.desktop.j2"
    dest: "{{ home_dir }}/{{ user_app_dir }}/{{ item.name }}.desktop"
  with_items:
    - "{{ chrome_apps }}"

- name: RSS links
  template:
    src: "templates/.newsboat/urls"
    dest: "{{ home_dir }}/.newsboat/"
  notify:
    - reload feeds

- name: GTK Bookmarks
  template:
    src: "templates/gtk-bookmarks.j2"
    dest: "{{ home_dir }}/.config/gtk-3.0/bookmarks"

    
- name: Install Oh My ZSH
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  args:
    creates: "{{ home_dir }}/.oh-my-zsh"
